import type { MentorProfile, MenteeProfile, VolunteerProfile } from "./types";

export const volunteerProfiles: VolunteerProfile[] = [
  {
    name: "Grace Wang",
    role: "Visual Designer",
    city: "Calgary",
    languages: ["Mandarin", "English"],
    focus: "Accessible event posters and resource graphics",
    availability: "Weekday evenings",
    status: "active",
  },
  {
    name: "Ethan Li",
    role: "Content Translator",
    city: "Toronto",
    languages: ["Mandarin", "English"],
    focus: "Housing and public-service explainers",
    availability: "Weekends",
    status: "active",
  },
  {
    name: "Maggie Chen",
    role: "Video Editor / Producer",
    city: "Vancouver",
    languages: ["Cantonese", "Mandarin", "English"],
    focus: "Short newcomer orientation videos",
    availability: "Project-based",
    status: "onboarding",
  },
  {
    name: "Jason Xu",
    role: "Social Media Operator",
    city: "Mississauga",
    languages: ["Mandarin", "English"],
    focus: "Event promotion and community updates",
    availability: "Two evenings per week",
    status: "active",
  },
  {
    name: "Annie Zhou",
    role: "Web Designer / Developer",
    city: "Waterloo",
    languages: ["Mandarin", "English"],
    focus: "Accessible frontend components and admin workflows",
    availability: "Flexible technical projects",
    status: "active",
  },
  {
    name: "Kevin Huang",
    role: "Mentor",
    city: "Ottawa",
    languages: ["Mandarin", "English"],
    focus: "Public services, transit, and civic learning",
    availability: "Saturday mornings",
    status: "active",
  },
  {
    name: "Sarah Liu",
    role: "Community Volunteer",
    city: "Burnaby",
    languages: ["Cantonese", "English"],
    focus: "Event check-in and participant support",
    availability: "Monthly events",
    status: "active",
  },
  {
    name: "Daniel Sun",
    role: "Content Translator",
    city: "Halifax",
    languages: ["Mandarin", "English"],
    focus: "Healthcare and student support resources",
    availability: "Weekends",
    status: "paused",
  },
  {
    name: "Rachel Ma",
    role: "Visual Designer",
    city: "Montreal",
    languages: ["Mandarin", "French", "English"],
    focus: "Bilingual social graphics and workshop slides",
    availability: "Sunday afternoons",
    status: "onboarding",
  },
  {
    name: "Brian Tang",
    role: "Web Designer / Developer",
    city: "Edmonton",
    languages: ["Mandarin", "English"],
    focus: "Supabase integration and analytics dashboards",
    availability: "Project-based",
    status: "active",
  },
];

export const mentorProfiles: MentorProfile[] = [
  {
    name: "Kevin Huang",
    city: "Ottawa",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Community life", "Public policy", "Transit"],
    background:
      "Public administration graduate who helps newcomers understand city services and local civic participation.",
    availability: "Saturday mornings",
    status: "matched",
  },
  {
    name: "Linda Zhang",
    city: "Toronto",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Housing", "Tax and benefits", "Libraries"],
    background:
      "Community tax clinic volunteer with experience helping newcomers organize documents and service questions.",
    availability: "Tuesday evenings",
    status: "active",
  },
  {
    name: "Patrick Lau",
    city: "Richmond",
    languages: ["Cantonese", "English"],
    areasOfSupport: ["Healthcare", "Community life", "Family services"],
    background:
      "Healthcare administrator familiar with public health navigation, family clinics, and local community programs.",
    availability: "Every other Saturday",
    status: "active",
  },
  {
    name: "Cindy Wu",
    city: "Waterloo",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Student support", "Campus life", "Housing"],
    background:
      "Former international student mentor supporting students with campus services and off-campus housing preparation.",
    availability: "Wednesday evenings",
    status: "matched",
  },
  {
    name: "Michael Chen",
    city: "Calgary",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Employment readiness", "Community life", "Volunteering"],
    background:
      "Nonprofit volunteer coordinator who introduces newcomers to community programs and volunteer pathways.",
    availability: "Sunday afternoons",
    status: "active",
  },
  {
    name: "Helen Guo",
    city: "Montreal",
    languages: ["Mandarin", "French", "English"],
    areasOfSupport: ["Public services", "Language resources", "Civic engagement"],
    background:
      "Settlement-sector volunteer familiar with multilingual service navigation and local participation opportunities.",
    availability: "Monday evenings",
    status: "active",
  },
  {
    name: "Andrew Yang",
    city: "Vancouver",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Rental preparation", "Transit", "Student support"],
    background:
      "Graduate student mentor who helps newcomers prepare rental questions and compare student support services.",
    availability: "Friday afternoons",
    status: "paused",
  },
  {
    name: "Sophie Lin",
    city: "Mississauga",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Family services", "Libraries", "Community programs"],
    background:
      "Parent volunteer with experience finding children’s programs, recreation subsidies, and public library services.",
    availability: "Thursday mornings",
    status: "active",
  },
  {
    name: "Raymond Ho",
    city: "Markham",
    languages: ["Cantonese", "Mandarin", "English"],
    areasOfSupport: ["Healthcare", "Senior services", "Community safety"],
    background:
      "Community health volunteer supporting older adults and families with public-service navigation.",
    availability: "Saturday afternoons",
    status: "matched",
  },
  {
    name: "Ivy Tan",
    city: "Halifax",
    languages: ["Mandarin", "English"],
    areasOfSupport: ["Student support", "Healthcare", "Civic engagement"],
    background:
      "Campus community volunteer helping students understand health insurance, campus offices, and local events.",
    availability: "Sunday evenings",
    status: "active",
  },
];

export const menteeProfiles: MenteeProfile[] = [
  {
    name: "Chen Yu",
    city: "Vancouver",
    preferredLanguage: "Cantonese",
    needs: ["Healthcare access", "Family doctor search", "Community programs"],
    urgencyLevel: "Medium",
    status: "reviewing",
  },
  {
    name: "Mia Zhao",
    city: "Toronto",
    preferredLanguage: "Mandarin",
    needs: ["Rental preparation", "Tenant resources", "Transit basics"],
    urgencyLevel: "High",
    status: "matched",
  },
  {
    name: "Leo Qin",
    city: "Waterloo",
    preferredLanguage: "Mandarin",
    needs: ["Campus life", "Student housing", "Health insurance"],
    urgencyLevel: "Medium",
    status: "matched",
  },
  {
    name: "Yiran Liu",
    city: "Calgary",
    preferredLanguage: "Mandarin",
    needs: ["Community life", "Library services", "Volunteer opportunities"],
    urgencyLevel: "Low",
    status: "submitted",
  },
  {
    name: "Amy He",
    city: "Mississauga",
    preferredLanguage: "Mandarin",
    needs: ["Tax documents", "Benefits letters", "Public service accounts"],
    urgencyLevel: "Medium",
    status: "reviewing",
  },
  {
    name: "Wilson Chan",
    city: "Richmond",
    preferredLanguage: "Cantonese",
    needs: ["Healthcare", "Senior services", "Community safety"],
    urgencyLevel: "High",
    status: "matched",
  },
  {
    name: "Nina Sun",
    city: "Ottawa",
    preferredLanguage: "Mandarin",
    needs: ["Public policy", "Civic engagement", "Municipal services"],
    urgencyLevel: "Low",
    status: "submitted",
  },
  {
    name: "Jasmine Wu",
    city: "Montreal",
    preferredLanguage: "Mandarin",
    needs: ["French-language services", "Healthcare", "Student support"],
    urgencyLevel: "Medium",
    status: "reviewing",
  },
  {
    name: "Eric Fang",
    city: "Edmonton",
    preferredLanguage: "Mandarin",
    needs: ["Winter safety", "Transit", "Community programs"],
    urgencyLevel: "Low",
    status: "submitted",
  },
  {
    name: "Tina Luo",
    city: "Halifax",
    preferredLanguage: "Mandarin",
    needs: ["Campus services", "Mental health support", "Volunteer pathways"],
    urgencyLevel: "Time-sensitive",
    status: "reviewing",
  },
];
